### PR TITLE
multi-page layout

### PR DESCRIPTION
**Pull request by aeon1234**
**preview**
https://aeon1234.github.io

### CODE REVIEW

**Comment by BigslimVdub** [comment]
Waiting on merge...

**Comment by iamsmooth** [comment]
How about some other community review/feedback?

**Comment by aeondocs** [comment]
Smooth, You may like to view the previous PR https://github.com/aeonix/aeonix.github.io/pull/115 

This will be the biggest and most important contribution to the website ever before. Should we celebrate it with a champagne?

**Comment by iamsmooth** [comment]
After merging previous PRs it looks like this has some conflicts now

**Comment by aeondocs** [comment]
Added latest updates as PR to aeon1234 branch. 
https://github.com/aeon1234/aeonix.github.io/pull/18

**Comment by aeon1234** [comment]
rebased

**Comment by aeondocs** [comment]
Looks good nice job everyone.

**Pull request merged**
