### PR TITLE
Update website to aeon-crypto repository as aeon.cash primary website

### PR DESCRIPTION
**Pull request by ivoryguru**
https://www.aeon-crypto.org/
https://github.com/ivoryguru/aeon-crypto

Edit: to clear confusion: this is to represent a "rebase" request I guess for this repository to use the above repository as the aeon.cash website. I am not sure how to make such a request so here I am submitting it.

### CODE REVIEW

**Comment by ivoryguru** [comment]
- Easily translatable/universally understandable messaging. All inclusive men women children. Humorous and fun. 
- Leaving AEON open and leaderless
    - distinguish Aeonix vs AEON
    - Dr. Paradoxically team, possible beautiful duality became regrettable disaster
- Empowering the community
- The future is in your hands
- Long-term stable links

**Comment by ivoryguru** [comment]
- @BigslimVdub 
I am just curious as to why not use the community site that was created in 2018 and refresh this?

Anyone is allowed to make PR to the site and it was created to add information outside the basic main webpage.


- @ivoryguru 
I believe the current website is sending a bad/wrong message about aeon. Also being the "official site" it should leave things in the hands of the community, not represent the community or speak for the community. AEON is leaderless and disorganized but the website is establishing itself as the one and only AEON.. "Download AEON" That is giving a bad impression. This is why the community is sitting in the back seat waiting for someone to pull them along. We don't have massive financial interests like other coins to make that possible. We need to jumpstart the community and get more websites such as the community site you mentioned. Leaders empower others and go out of their way to help them achieve their full potential. That is our main goal for the website.
These are not just empty criticisms and now is not the time for "well there is no hope la dee da". AEON is possible. I have created the website here https://github.com/ivoryguru/aeon-crypto and it is available to view here https://aeon-crypto.org/. It is finished so please make more comments about this request here or on github PR https://github.com/aeonix/aeonix.github.io/pull/111 .
I will do use the community pages as well. Like I said, I want to see more sites run by community members and plan to help out there as well. That is a great platform for rapid updating and sharing new ideas/ projects, writing articles about aeon and every thing can be run on a massive network of community projects.
I hope my message is being expressed clearly and respectfully... Thank you for reading and asking such important questions.

**Comment by ivoryguru** [comment]
Discussion on discord:

rrrrr
does anyone believe aeon dynamic block size limit will make blockchain grow too quickly ?
if the network ever hits exponential growth, blockchain size will outpace mobile phone storage growth

<bigslim[m]> Donâ€™t need to worry about mobile storage if everyone transacting on a mobile device uses a remote node...
<bigslim[m]> Insert cakewallet here

rrrrr01/12/2021
I thought the idea was to have nodes running on the phones
That was my understanding of mobile friendly

irc.freenode.net#aeon
BOT
01/12/2021
<bigslim[m]> Yes but itâ€™s highly doubtful a majority of people would do that. A remote node is 90% easier and people feed off of easy.
<bigslim[m]> Especially if you run your own node at home and can use your IP for the remote node
<bigslim[m]> IMO thatâ€™s the best way to do it

rrrrr01/12/2021
I wish the focus was still to make that a possibility. If few will run nodes on their phone then most will use another crypto anyways. This is what will make aeon unique.
People can live freely entirely from their phone. Take the blockchain wherever they go.

camthegeek01/12/2021
data caps on mobile suck.

rrrrr01/12/2021
Yup but think of the possibilities... That is the true spirit of crypto to run your node and participate in the network.

irc.freenode.net#aeon
BOT
01/12/2021
<bigslim[m]> I think a majority of people do not want to run a node on their phone today
<bigslim[m]> That may have been the case in 2014/15

camthegeek01/12/2021
sure it is. major cellular service providers typically limit lines to specific amounts of data per month. so that aeon node you run, it was 4gb to fully synchronize.. then you end up sharing the data with hundreds of others each month.. costing you maybe anywhere between 500mb to 8gb of data.. and if you're capped at 5gb, you're screwed on the first month.
you could disable the p2p piece where you let others download from you and it saves you.. but then you're not entirely participating like you should be lol
My statements are purely based on my experience with cellular providers here in the states and the small caps we have.
oh these guys have swapped to this unlimited bs.. fast unlimted data until a certain point and then it runs like dog shit afterwards :smile:

irc.freenode.net#aeon
BOT
01/12/2021
<bigslim[m]> Itâ€™s like 5gb at 4g then everything after at 3g on a good day
camthegeek01/12/2021
I guess. I swapped to a prepaid option years ago that has plenty of data. wireless plans always gave me a headache.
additionally, I have no desire to run a node on my phone
rather just open a wallet, it sync's and I spend.

rrrrr01/12/2021
I see

rrrrr01/12/2021
So what is the deal with the mobile freindlyness?
I realize your two opinions don't represent the entire AEON community but, if we are just going to connect a to remote node, why not use monero or bitcoin?

irc.freenode.net#aeon
BOT
01/12/2021
<bigslim[m]> Thatâ€™s the million dollar question
<bigslim[m]> If I were someone wanting to send large amounts of illegal monies from something I would not use monero as an exit course. I would use one of the 265 CN fork coins exiting to fiat to fund activities. Hence the need for CN coins other than monero.
<bigslim[m]> But thatâ€™s thinking in the mindset of the government
<bigslim[m]> Rambling on more...

rrrrr01/12/2021
Haha

irc.freenode.net#aeon
BOT
01/12/2021
<bigslim[m]> If you were to poll 100 random people about using crypto and if they would rather open a mobile wallet and send money now, or open a mobile wallet and send money in 20-30min, by bet is on the open wallet and send money now choice.
<bigslim[m]> Without running a node 24/7 itâ€™s pretty much not possible to use a mobile daemon and option 1
<bigslim[m]> Maybe in 10 years with 100x more compute power in a cellphone it would be possible
<bigslim[m]> But then you have the issue cam described with data usage and also batter consumption. A mobile wallet with remote note just fixes all those issues and is probably why very few crypto projects have pursued that
<bigslim[m]> * But then you have the issue cam described with data usage and also battery consumption. A mobile wallet with remote note just fixes all those issues and is probably why very few crypto projects have pursued that
<bigslim[m]> * But then you have the issue cam described with data usage and also battery consumption. A mobile wallet with remote node just fixes all those issues and is probably why very few crypto projects have pursued that
<bigslim[m]> It can also be solved with off chain transactions like btc and some others are doing. Iirc monero was looking at this with tarai?
<bigslim[m]> However for a true trustless, permission-less transaction one fully needs a full node and wallet on the device they are transacting on. My workaround is running a full node at home and connecting wirelessly via mobile app that way I am trusting myself when making a transaction, not a third party.

rrrrr01/12/2021
Totally agree. Maybe we are not giving Aeon the right brand then. Maybe instead of advertising as mobile friendly, which sounds hip but just doesn't really make sense, we should stick to stable secure codebase merging from experimental monero + communirty driven + fair launch.. I don't really see how this mobile friendly trend can take off for aeon. Plus "Aeon" and stability/secure sounds like a nice name as is Aeon for ages.

irc.freenode.net#aeon
BOT
01/12/2021
<bigslim[m]> Almost all crypto is “secure”. Most are stable
<bigslim[m]> In the end, aeon is more mobile friendly than any other crypto sans not having an iOS wallet.
<bigslim[m]> Itâ€™s also very cheap to support with any exchange/vendor/marketer
<bigslim[m]> Plus itâ€™s a legitimate fallback to monero

**Comment by ivoryguru** [comment]
Other discussion
rrrrr01/13/2021
PR is coming the work is ready it is just a matter of clicking a button.
Not same issue, friend.. I have a solution. That is the major difference

irc.freenode.net#aeon
BOT
01/13/2021
<bigslim[m]> Well then do that and then we can discuss
<bigslim[m]> No sense saying what could be done because itâ€™s limitless

rrrrr01/13/2021
Well we are at the PR for the PR stage haha

irc.freenode.net#aeon
BOT
01/13/2021
<bigslim[m]> Lol
<bigslim[m]> People donâ€™t want to discuss theories

rrrrr01/13/2021
I will wait to see what are people saying.. maybe it is a terrible idea.

irc.freenode.net#aeon
BOT
01/13/2021
<bigslim[m]> They are more than happy to give opinions on proposed changes

rrrrr01/13/2021
I understand people are distraught from fluff talk
The proposed change is here aeon-crypto.org

irc.freenode.net#aeon
BOT
01/13/2021
<bigslim[m]> Because they know they are discussing an actual change that can happen tomorrow not in 2024

rrrrr01/13/2021
Yeah well this is a big change .. slow and steady or people will feel left out of the process.
There needs to be time for everyone to speak up .. Obviously not everyone can agree but at least they have an opportunity to speak.
The site is untranslateable due to stoffu's PR. It is full of complicated cryptographic language and it largely overrode previous translation work. He should have kept this on his personal blog rather overwrite the translated work. That is why the new site is intended to be even more translatateable because there is simpler language and it is not intended to change often.

camthegeek01/13/2021
What can't be translated? Give me details and I'll resolve. Not rocket science lol

rrrrr01/13/2021
No I mean the language is just very technical it is hard to find a good translation. The website structure is well designed I intend to maintain the same jekyll page.lang setup. I thought that was very clever.
Most of the website simple has no translation
I might be able to ask my friend thinkcat23 for a Chinese translation
Big slim do you ever play age of empires

camthegeek01/13/2021
I would suggest moving things from front page to another page. Im not sure if I setup an external layout for it but I can

rrrrr01/13/2021
agreed but why not offload onto community websites for everyone to contribute?
we unfortunately are forced to have a "official" website. It should be very liimited in its expression. The rest should be directed by the community in a true decentralized fashion.

irc.freenode.net#aeon
BOT
01/13/2021
<bigslim[m]> I do not may many PC games. 20yrs ago yea.
<bigslim[m]> We made that community site so others can make changes and commit but only a few people added a little content of theirs here and there.
<bigslim[m]> We have Chinese translation already   Iirc itâ€™s HK Chinese not mandarin or traditional

rrrrr01/13/2021
They just released a definitive edition it is too good. Have been playing it often. The community site is awesome planning to make some contributions one day. I want to record the history of aeon in a few pages I think that would be interesting and entertaining.

rrrrr01/13/2021
We'll also need to make a multi sig guide one day like you mentioned

BigSlim01/13/2021
Updating a TON of stuff on https://aeoncommunity.github.io/
AEON Community Pages
AEON Community Pages
A compilation of information, links, and recognition of Aeon accomplishments
so outdated
looks like bot ded again

rrrrrYesterday at 10:27 AM
dope here is repo for aeon-crypto.org
https://github.com/ivoryguru/aeon-crypto
GitHub
ivoryguru/aeon-crypto
Contribute to ivoryguru/aeon-crypto development by creating an account on GitHub.

camthegeekYesterday at 10:32 AM
anyone on irc able to confirm if bridge is down?
nvm, confirmed it is, give me a moment
bridge is back up. @rrrrr @BigSlim can repost your stuff.

rrrrrYesterday at 10:43 AM
ok cool

bigslim : "Updating a TON of stuff on https://aeoncommunity.github.io/ so outdated
looks like bot ded again
"
AEON Community Pages
AEON Community Pages
A compilation of information, links, and recognition of Aeon accomplishments

rrrrrrrrr : " dope here is repo for aeon-crypto.org
https://github.com/ivoryguru/aeon-crypto"

irc.freenode.net#aeon
BOT
Yesterday at 10:48 AM
<bigslim[m]> I really forgot how much stuff was on that community github holy cow
<bigslim[m]> So much more to update too but I added a bunch of stuff.

irc.freenode.net#aeon
BOT
Yesterday at 11:08 AM
<bigslim[m]> Contemplating to sell my 1070ti for like $400 and get a cheapo card to boot with like gt750

tyuvvdgzkpYesterday at 6:08 PM
was ~2 wks away from discord. hello again.
i've been following the activities of the last few days with interest. i think a change to a multi-page site would be very appropriate to give the site a better overview and also gradually add more content.  i like the rather general and easier to understand language on your proposed website. that would definitely be something i would like to see additionally on the official site. but the design is a bit too plain for me, so unfortunately you don't convince me that much. and i would like to keep the actually all content of the current site additionally, as i'm sure many people are interested in that as well. i've been thinking about it a lot in the last months and i think we should gradually implement small changes via PRs, so that we can discuss them better. i'm sure that several people could contribute good ideas here. probably we should start by converting the website into a multi-page site. unfortunately, due to the current implementation of the translation feature, there is no way to split the website into multiple files, as far as i know. so we would have to have everything in one file and show/hide the individual "pages" via js or css.

BigSlimYesterday at 6:23 PM
@camthegeek did you have the ability / time to compile and submit a pr for multi page and keeping the same ease of editing like we have now for aeon.cash?

rrrrrYesterday at 6:24 PM
It is finished use as you may https://github.com/ivoryguru/aeon-crypto
GitHub
ivoryguru/aeon-crypto
Contribute to ivoryguru/aeon-crypto development by creating an account on GitHub.

tyuvvdgzkpYesterday at 6:24 PM
if I remember correctly he needs access to the repo

camthegeekYesterday at 6:31 PM
fwiw, it's completely do-able (multi-page even with current lang setup). give me a week or three and I'll get it done
if smooth could fix the dns on aeon.cash and toss me some privileges on the web repo, I could even setup a better language system (needs access to github ci, or go the old route at travis-ci)

tyuvvdgzkpYesterday at 6:34 PM
ah i knew there was a better implementation if you had privileges on the repo.

camthegeekYesterday at 6:35 PM
yeah, see masari's website for an example. same setup as aeon but with better lang system

tyuvvdgzkpYesterday at 6:35 PM
yes had a look in the masari repo back then. way better.

camthegeekYesterday at 6:36 PM
creating external/additional pages there is a breeze. would be good to have it here too

rrrrrYesterday at 6:37 PM
That is how this page is setup on aeon-crypto
We need to activate the community. Their is too much waiting on smooth. people are sitting in the back seat waiting for smooth to carry them along

camthegeekYesterday at 6:41 PM
it's been that way since 2017 lol
I took a big break from aeon and the community because of this reason :smile:

rrrrrYesterday at 6:42 PM
that is why the "official" site needs to leave room for people to contribute elsewhere. It needs to say "their is no one charge but you now go and contribute". That is it not Mobile freindly this private that

camthegeekYesterday at 6:43 PM
guess you can say it's been that way since before 2017 too

rrrrrYesterday at 6:44 PM
I know and I feel that it is important to reactivate the community. The website should not make bombastic claims about "enabling the world on mobile friendly devices". We are not doing that. We are mobilizing a community

tyuvvdgzkpYesterday at 6:44 PM
yes things like not having the ssl fix yet is sad

rrrrrYesterday at 6:45 PM
it is not smooth fault. It is just the wrong message being sent to the general public. We are trying to be like the big money when we are just some casual crypto heads.
people come expecting new features

tyuvvdgzkpYesterday at 6:46 PM
@rrrrr  you have a point here . we should probably word it more to lightweight instead of mobile friendly.

camthegeekYesterday at 6:47 PM
You can try to fix that website all you want. It's not that helpful to aeon at all though. you need some services. you need some aeon-education. you need active marketing, etc..  aeon.cash can remain the same for the next 10 years and that's fine. if you google aeon crypto, you don't get anything outside of aeon.cash that is community owned.
if someone were researching this, they wouldn't have much hope with finding ways to use it, finding fan made sites/content, etc.. it just appears as a purely.. boring unattractive coin lol

rrrrrYesterday at 6:48 PM
boring unnattactive is the key
people are entrusting their money in this coin
they want to know that tomorrow it is still there
that is all that is important here
new flashy features are only a security risk

camthegeekYesterday at 6:50 PM
so pour money into a coin.. and the only thing you can do with it is.. send to others and trade it for bitcoin?

rrrrrYesterday at 6:51 PM
that is money right?

camthegeekYesterday at 6:51 PM
I can blow money on hookers if I wanted too..

tyuvvdgzkpYesterday at 6:52 PM
like any other coin. it's mostly speculation anyway.

camthegeekYesterday at 6:52 PM
(cant spend aeon on hookers. mostly just gamble on betaeon.win)

rrrrrYesterday at 6:53 PM
I believe that time will come cam. There can only be so many fair-launched coins. I believe Aeon will be one to survive.

tyuvvdgzkpYesterday at 6:56 PM
regulation could limit the use of cryptocurrencies quite a bit. maybe in the future it will be possible to buy things on larger platforms with several cryptocurrencies, but in my opinion it will remain mostly speculation.

rrrrrYesterday at 6:57 PM
That is fair. we are still waiting for the hammer of gov to come down on this crypto experiment.
but anyway I did something for AEON I did not just talk about it. The website is here it is ready for the community to accept or decline https://github.com/ivoryguru/aeon-crypto
GitHub
ivoryguru/aeon-crypto
Contribute to ivoryguru/aeon-crypto development by creating an account on GitHub.

tyuvvdgzkpYesterday at 7:01 PM
aml is difficult to reconcile with cryptocurrencies and so I'm not sure if we will ever find legal use-cases out of heavily regulated exchanges.

rrrrrYesterday at 7:29 PM
The request is made. https://github.com/aeonix/aeonix.github.io/pull/111 I don't know how this can ever be decided. That is why a primary site for AEON should just be a blank page. Leave AEON to the world.
GitHub
Update website to aeon-crypto repository as aeon.cash primary websi...
https://www.aeon-crypto.org/
https://github.com/ivoryguru/aeon-crypto

**Comment by ivoryguru** [comment]
@aeon1234 Do you see this as having any potential or is just a total failure? Perhaps some changes can be made.. It is far easier to build up from a blank slate than to patch up a broken website.

**Comment by BigslimVdub** [comment]
> @aeon1234 Do you see this as having any potential or is just a total failure? Perhaps some changes can be made.. It is far easier to build up from a blank slate than to patch up a broken website.

what part of the website is broken though?

**Comment by ivoryguru** [comment]
There is #106 #107 #108 to begin. I can name quite a few other design things such as bad color matching with logo,  blur.png, and     `background-color: #08b4da` on differences section , mismatched fonts `<span class="fa fa-windows">&nbsp;&nbsp;Windows, 64-bit</span>`  the ugly mcdonalds themed header. The structure of the website is simply poorly designed. The code is poorly written: Everything including all translations are in one giant file config.yml. The website is terrible believe me. If that is ok with everyone, it is ok with me as well. but believe me this website needs a lot of work. @BigslimVdub we need you on the frontlines you are the master of PR.

**Comment by ivoryguru** [comment]
Here are 3 websites I see as model 
https://atom.io/
https://www.ruby-lang.org/en/
https://www.audacityteam.org/

What is common between these three and different from aeon.cash?

Big DOWNLOAD HERE button

Simple straightforward description (1 sentence)
- "Free, open source, cross-platform audio software: Audacity is an easy-to-use, multi-track audio editor and recorder for Windows, macOS, GNU/Linux and other operating systems."
- "A hackable text editor for the 21st Century"
- "Ruby is... A dynamic, open source programming language with a focus on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write."

Latest version information

Multi-page layout

---

all of these are in aeon-crypto

**Comment by aeon1234** [comment]
some parts of the code may be a bit messy at the moment and that's why I too would have preferred to start from scratch. but it's nothing that can't be fixed and I also think that a gradual change is better.

> Big DOWNLOAD HERE button
> 
> Simple straightforward description (1 sentence)
> 
> - "Free, open source, cross-platform audio software: Audacity is an easy-to-use, multi-track audio editor and recorder for Windows, macOS, GNU/Linux and other operating systems."
> - "A hackable text editor for the 21st Century"
> - "Ruby is... A dynamic, open source programming language with a focus on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write."
> 
> Latest version information
> 
> Multi-page layout

all bullet points can be solved by anyone via PR.
i will create a PR tomorrow with the last bullet point (multi-page layout).

**Comment by ivoryguru** [comment]
Awesome I am excited to review.

**Comment by SomaticFanatic** [comment]
I don’t like this change. The current website works fine.

**Comment by ivoryguru** [comment]
Nice, thanks for sharing. Anything you don't like in particular? Have you tried to have an open mind? It was designed with these goals in mind 

- Easily translatable /universally understandable messaging
- Leaving AEON open/no officiality
- Empowering the community
- Long-term stability

**Comment by SomaticFanatic** [comment]
“Have you tried to have an open mind?”

Personal attacks. Nice.

**Comment by ivoryguru** [comment]
Sorry, it is an honest question not an attack. Seems your comment only says the website is fine but not why it is fine or why it shouldn't change. It would be interesting to hear your perspective on this.  Is there something you don't like about it?

**Comment by aeon1234** [comment]
the PR only overwrites the readme file and replaces it with a note to your website. i don't quite know what the purpose of this is. it doesn't look like an improvement to me.

about your website i can only say that i like the design even less than the current one. i like parts of your content, but you could just embed them here via PR?

and in my opinion nothing is gained by switching from one github account to another. smooth may be a bit taciturn and sometimes long winded, but there have never been any problems (as far as i know). he's around in cryptospace for just under 10 years, that's a long time. on top of that this can lead to a split in the community which we should rather avoid.

i hope that wasn't offensive or anything. i really like your energy and i really hope you stay with the community for a long time :)

**Comment by ivoryguru** [comment]
> the PR only overwrites the readme file and replaces it with a note to your website. i don't quite know what the purpose of this is. it doesn't look like an improvement to me.

This has nothing to do with smooth or switching accounts, it is just a pr to replace the files here with the ones in aeon-crypto. The PR is just symbolic because bigslim said he wanted to see a PR. I have no problems with smooth, they are doing well as maintainer I hope they will continue. I would not have started to work on AEON if I did not already believe in smooth's decision making.

Finally, I have no intention of any community "hard-fork" and I understand that nothing is going to happen here.. but it is good to see some productive discussion such as multi-page layout and other ideas.

**Comment by ivoryguru** [comment]
Thanks for the nice compliment as well, I enjoy working on aeon and meeting new people like you and big slim online. I admire the careful work that stoffu and smooth have put into aeon. I have studied many coins and I truly believe that aeon is the most ideal cryptocurrency. My day job is also quite boring and my boss doesn't like when I work, very strange.. So I hope one day I have enough money to quit so that I can study the c++ source code.. a language I have never studied and seems quite complex but cannot be impossible.

**Comment by aeon1234** [comment]
>The PR is just symbolic because bigslim said he wanted to see a PR.

oh, i wasn't aware of that. but maybe an issue would have been an alternative, at least that would have saved me some confusion.

>so that I can study the c++ source code

just start if you have time on work :)

>

**Pull request closed without merging**
