### PR TITLE
fix summary paragraph

### PR DESCRIPTION
**Pull request by camthegeek**
summary paragraph in english is duplicate of last feature as reported by discord user cryptozi#6656. summary paragraph in other languages appear to be correct and this makes it match up.

### CODE REVIEW

**Comment by BigslimVdub** [comment]
Ready to merge no conflicts

**Comment by iamsmooth** [comment]
Not a fan of the litecoin reference as it doesn't really describe the situation with AEON very well. Apart from the name I'm not sure I can actually think of anything about litecoin that is lighter than Bitcoin. The PoW is _heavier_, the block time is faster (meaning a larger blockchain for equal usage, and more work for header syncs even above the difference in PoW) and the rest is identical.

By contrast AEON actually has significant lightness advantages over Monero (and on top of existing advantages, the PoW will be massively lighter after the K12 fork)

**Comment by BigslimVdub** [comment]
“Litecoin seeks to be a lightweight-Bitcoin”

That doesn’t mean that they are. Many projects “try” to be something but never end up actually accomplishing that vision.

**Comment by camthegeek** [comment]
> Not a fan of the litecoin reference as it doesn't really describe the situation with AEON very well. Apart from the name I'm not sure I can actually think of anything about litecoin that is lighter than Bitcoin. The PoW is _heavier_, the block time is faster (meaning a larger blockchain for equal usage, and more work for header syncs even above the difference in PoW) and the rest is identical.
> 
> By contrast AEON actually has significant lightness advantages over Monero (and on top of existing advantages, the PoW will be massively lighter after the K12 fork)

I had zero involvement writing the summary; it was a copy/paste from the previous site that had been on there for years. While I can change what it says with this PR, I think a new issue should be opened to discuss what the summary and other key points say, especially in preparation for the K12 proof of work algorithm switch.

**Comment by iamsmooth** [comment]
@camthegeek Thank you for the explanation. I wasn't aware (nor was it clear from the commit here) it was existing text. In that case I would agree replacing it should be a different PR.

**Pull request merged**
