### PR TITLE
Structure update + additional language support

### PR DESCRIPTION
**Pull request by camthegeek**
To start off with, this PR gives the website a slight structure overhaul. It does not change anything that appears on the front end, other than language switcher and language, when switched.

This pull request sections off the page header and footer from _layouts/default.html and places them into _includes/header.html and _includes/footer.html. They are included in the default layout. This will make it easier to find what areas of the page need edited. In addition to moving header and footer, I also placed the banner section directly in index.html. However, in the future, I believe it would be best to move this to it's own file as well. 

Multiple languages are now supported. As Github does not allow the use of unapproved plugins such as, jekyll-multiple-languages-plugin (same plugin Monero uses), I had to go with another option. The method provided in this PR utilizes _config.yml and contains sections to be translated that pair up with each section of the website. It is a rather simple approach. 

Included with this PR is also a README which explains how to translate as well as 4 additional languages made by the AEON community in the past month. I strongly believe that future translations using this method will be much easier and convenient as translators are not dealing with a large amount of HTML code.

Desktop:
desktop Image
Mobile:
mobile Image

### CODE REVIEW

**Comment by aeon1234** [comment]
very nice work. thank you.

but do we need all these separate index.[lang].html files if every translation is defined in _config.yml? is there maybe a way to have only one index file? because if we make changes in html then we have to update every index.[lang].html file, which seems like bad practice.

**Comment by camthegeek** [comment]
> very nice work. thank you.
> 
> but do we need all these separate index.[lang].html files if every translation is defined in _config.yml? is there maybe a way to have only one index file? because if we make changes in html then we have to update every index.[lang].html file, which seems like bad practice.

We could have one index file if someone would be willing to toss me an API key to hook Travis-CI up to the repository. This will allow us to use the popular jekyll-multi-language-plugin as it is not natively supported by Github. Going this route, we could easily have the master branch show the source and an off branch that would serve the static site. 

The other option is to rename the files from index.[lang].html to just [lang] that way browsing (and directory) appears as /es /fr /eo etc.

**Comment by stoffu** [comment]
Indeed, having to maintain index.[lang].html for every language seems quite problematic/undesirable, especially considering that those files are identical except for the language specification in the beginning. After a brief web search, I came across another solution https://github.com/ruby-gettext/jekyll-task-i18n which seems to work just fine with GitHub pages. Maybe can you give it a try?

**Comment by camthegeek** [comment]
`there must be some other better solution`

solution found.

**Comment by stoffu** [comment]
@camthegeek 
Sorry for my ignorance, I realized after doing some research how tricky it is to do multilanguage on GitHub Pages + Jekyll. I couldn't find any simple solution better than yours.

All the `index.[lang].html` files having identical content seemed like a big maintenance burden to me at first, especially considering addition/removal of contents, but on second thought it seems doable since one only needs to copy those files properly.

Can you reopen this PR? Thanks again for your effort.

**Comment by BigslimVdub** [comment]
Thank you Cam for taking time to reopen and look at this again.

**Pull request merged**
