### PR TITLE
multi-page layout

### PR DESCRIPTION
**Pull request by aeon1234**
**preview**
https://aeon1234.github.io/

### CODE REVIEW

**Review by BigslimVdub — APPROVED** [review]
Looks good. It appears a good start at the website refresh with multi page layout.

**Comment by ivoryguru** [comment]
It is a good start and works for now. I would like this better if there were truly multiple pages and not css tricks. That way if the website is to grow larger in the future the entire website does not need to be downloaded at one time. You will need multiple layouts  in `_layouts` see  https://jekyllrb.com/docs/pages/

**Comment by ivoryguru** [comment]
https://jekyllrb.com/docs/layouts/

**Review by ivoryguru — CHANGES_REQUESTED** [review]
See other comments

**Comment by aeon1234** [comment]
I'm not sure how we should design this with our current messy implementation of translation.
that's why I did it this way.
any idea?

**Comment by ivoryguru** [comment]
I understand your concern. This is the point I make about starting from scratch.  It sounds like we should fix translation before moving forward. Otherwise, the website will continue to become more confusing and harder to work with.

**Comment by BigslimVdub** [comment]
IMO the translations are quite easy to do right now since everything is in one file and grouped together. One can easily add a new language with editing 3 files and making a pr

**Comment by aeon1234** [comment]
I said that it's messy because we currently have to add way more files in a real multi-page layout (exactly one file for each page and each language).
but I will have a look at this again and hopefully come with a better solution.

**Comment by ivoryguru** [comment]
@bigslim That is nice for now, I agree, but having everything in one giant file is not an organized/quick approach. It is also not extendable.  Every page of the entire website will have to be in one file content.html and will be loaded when visited. It will work but it will be slow and rely on css+javascript instead of using jekyll tools that are already available to us for multi pages and translations.

If this is okay for everyone, I am happy to approve but it is not the way of the future. Eventually this will have to be redone.

**Review by ivoryguru — APPROVED** [review]

**Comment by ivoryguru** [comment]
@aeon1234 is there somewhere we can preview these changes? I would like to see how it is to use.

**Comment by ivoryguru** [comment]
Also, can you add information to the read me about how to add a new page or remove a page that is no longer needed?

**Comment by SomaticFanatic** [comment]
I think this change is unneeded. People on their phones are much much more likely to keep scrolling to look at more content than to click the hamburger icon to click on additional pages.

**Comment by aeon1234** [comment]
@ivoryguru I added a preview link on top comment
@SomaticFanatic i can only speak for myself here, but i would like to see and also add more content to the website and don't think we need an even longer scrollbar. however, i think the mobile menu could use some reworking (especially in terms of size of links) to make it easier to use.

**Comment by ivoryguru** [comment]
@aeon1234 thanks. It is a good start but like I was saying, if we are building for the future it will need to be multiple pages. Transitions between pages are already very slow so I cannot approve this PR.  If you want to go through the trouble to make multiple layouts, I won't stop you; but, it is already finished at https://github.com/ivoryguru/aeon-crypto so feel free to fork and modify as you please. I know you are all stubborn for change but I am really trying to do some good for everyone so please be open for change.

**Review by ivoryguru — CHANGES_REQUESTED** [review]
Too slow

**Comment by aeon1234** [comment]
the survived scroll animation had an unwanted behavior (it was always on for 1 second). i have adjusted it a bit and now there should be no more lags when trying to scroll manually after clicking a menu item. please try the preview again.

otherwise this way of loading and displaying is a bit faster than reloading single pages from the server/cache every time. of course everything is loaded the first time but that's what it does on the current live page as well.

**Comment by ivoryguru** [comment]
Much better.. I thought that was strange

**Comment by ivoryguru** [comment]
Does that need another commit or is it here already?

**Comment by aeon1234** [comment]
updated commit (after messing around :laughing:)

**Comment by ivoryguru** [comment]
This is working much better. Is there anything else we need to add to this or are we just going for the multi-page _functionality_ @SomaticFanatic

**Comment by SomaticFanatic** [comment]
As stated earlier, I think this change is a negative one. Longer scroll is better than multiple pages for phones. A lot of normies don’t even click on hamburger icons.

**Comment by ivoryguru** [comment]
Haha that is a good point, it is possible to maintain a longer front page still. I believe the goal for this is to only set up the functionality for multipages so possibly @aeon1234 will have to comment, they are building a better code for this I believe.

**Comment by aeon1234** [comment]
i don't see any other way than splitting the website to create some order and add more content in the long run. for example there are links to exchanges and a part of the community pages in the footer. first of all that rather doesn't belong there and secondly you can hardly add more links and categories to keep it from getting completely overcrowded. and unfortunately you have the same problem with the other categories too without the website being as long as a book afterwards.

unless of course no one wants to add anything more to the website then it can stay that way. but that's not my goal. besides most websites have a menu. if normies don't click on it they miss half the internet.

**Comment by ivoryguru** [comment]
Something might be possible, but first we would need to have the pages to work with. Have you made any progress on that front?

**Comment by aeon1234** [comment]
should be finished.

**Comment by ivoryguru** [comment]
Nice, this is really well done. It is perfect. I think now is a good time to discuss some of what @SomaticFanatic writes. For example, features section may be fine staying together on the first page. Not enough content for standalone page. I made a PR on your branch if it is desired.

Also will want to think about what to do with footer.

**Comment by aeon1234** [comment]
>I made a PR on your branch if it is desired.

I think we should keep these two PRs separate.

and I agree that we can include the content of `features` in `home` page as long as it doesn't contain more content.

I am open to a discussion. so it would be great if others could give their opinion on this.

**Comment by ivoryguru** [comment]
Ok, I don't see what harm it would cause but that is fine to make a seperate PR too.

**Review by ivoryguru — APPROVED** [review]

**Comment by ivoryguru** [comment]
@aeon1234 told me that they are working to combine features and differences into the home page.

**Pull request closed without merging**
