### PR TITLE
Banner for fork announcement + major rewrite of 'differences' section

### PR DESCRIPTION
**Pull request by stoffu**
Screen Shot 2019-09-30 at 14 16 02

Screen Shot 2019-09-30 at 14 16 19

Some notes on the rewrite:

- The notion regarding blockchain pruning was removed since Monero does have the feature which is not ported to Aeon yet.

- The notion of Litecoin seeking to be lightweight-Bitcoin was reworded since quite the opposite is true; i.e. Litecoin is heavier than Bitcoin in every respect (block time & PoW).

- I used Google translation for the fork announcement text. Translations of the rewritten part should be done by volunteers later.

Opinions and feedback are welcome.

### CODE REVIEW

**Comment by stoffu** [comment]
Added notion about RingCT's hidden inflation risk and smaller ring size.

The current look:
Screen Shot 2019-10-01 at 13 27 15

**Comment by stoffu** [comment]
Replying to @BigslimVdub's comment https://github.com/aeonix/aeonix.github.io/commit/c35a8f4f10ca0c1ba59ec4b07872afd5d66b7a32#commitcomment-35294646

(Please post to this PR thread next time)

> Yea definitely needs all translations before merging this. It’s not acceptable to have English for all others imo.
> ## Edit
> 
> Recommend these changes:
> 
>     * "We believe ASIC resistance is ultimately futile while imposing various forms of undesirable cost. Our ASIC-friendly PoW (KangarooTwelve) allows for faster verification of the blockchain. This also helps to stabilize the protocol as the need for PoW-change hard forks is eliminated."
> 
>     * "Monero's RingCT which encrypts transaction amounts adds significant cost to verification. We choose not to use RingCT as we believe the practical level of privacy and security can still be achieved without it."
> 
> 
> Add back in section 4 with:
> 
>     * "A faster sync is provided by a smaller total blockchain and lighter PoW, improving sync times by up to 10 times or more on lower-end devices when compared to other CryptoNote blockchains."

- Translating all these text to all the target languages seems to take quite some time. It is important that this fork announcement gets released ASAP since the fork date is nearing. I think it's OK to leave them not translated for the time being, and add translations later as volunteers offer their effort.

- I think "help do something" is grammatically also correct and interchangeable with "help to do something"

- I think "privacy and security" is redundant, just mentioning "privacy" feels fine to me. All crypto projects rely on the same crypto primitives that are believed to be secure. And you can't guarantee 100% security for any system.

- I'm against using the old item 4 about faster syncing. The fact that Aeon's blockchain is smaller and easier to sync is partly due to its adoption level being simply lower than Monero. It's meaningless to compare sync time between Monero and Aeon when the adoption levels are completely different.

**Comment by aeonix** [comment]
@stoffu Would the sync be faster with (hypothetical) similar usage because of smaller ring size and lack of RingCT? I don't know the numbers but if that is indeed the case, it seems fair to state it since this type of efficiency is part of the trade offs being made with lesser default privacy protections.

**Comment by iamsmooth** [comment]
@stoffu Would syncing be faster in the (hypothetical) situation of similar usage due to the lack of RingCT and smaller ring size? If so that seems fair and useful to mention as an advantage since it is part of the tradeoffs being made for lesser default privacy.

**Comment by stoffu** [comment]
@iamsmooth 
Good point, yes, that would be the case. I've added a sentence at the end mentioning it (I didn't make it another bullet item because fast sync itself isn't a design choice, it's the result of the above-mentioned choices).

I've also removed the reference to Bitcoin/Litecoin as it doesn't seem appropriate on a second thought. Aeon doesn't need to be silver to Monero's gold, **I genuinely believe it can surpass Monero**.

**Comment by BigslimVdub** [comment]
Looks good. I would approve that as it stands.

**Pull request merged**
